general:
  enable_incomplete_verification: true
# model:

data:
  dataset: MNIST
  start: 0
  end: 1000
  std: [1.]
  mean: [0.]
  # select_instance: [98]
specification:
  epsilon: 0.3
  # epsilon: 0.1
  norm: .inf
attack:
  # pgd_restarts: 50
  pgd_order: skip
solver:
  batch_size: 1
  alpha-crown:
    share_alphas: true
  beta-crown:
    iteration: 20
bab:
  timeout: 180
