# Configuration file for running the cifar100_tinyimagenet_resnet benchmark (tinyimagenet model).
data:
  dataset: Tiny
  num_outputs: 200
  start: 272  # Subject to change.
  end: 442
# model:
#   onnx_optimization_flags: merge_bn
specification:
  norm: 2  # Linf norm (can also be 2 or 1).
  epsilon: 0.141176471  # epsilon=36./255.
attack:
  pgd_order: skip
  # pgd_order: middle
  # pgd_restarts: 10
solver:
  batch_size: 1024
bab:
  timeout: 180